---
sudo: required
language: python
services: docker

env:
  - version=">=2.7,<2.8" distro="alpine-latest" expectation="fail"
  - version="" distro="alpine-latest" expectation="fail"
  - version="devel" distro="alpine-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
  - version="" distro="alpine-edge" expectation="fail"
  - version="devel" distro="alpine-edge" expectation="fail"
  - version=">=2.7,<2.8" distro="archlinux" expectation="fail"
  - version="" distro="archlinux" expectation="fail"
  - version="devel" distro="archlinux" expectation="fail"
  - version=">=2.7,<2.8" distro="centos-6" expectation="fail"
  - version="" distro="centos-6" expectation="fail"
  - version="devel" distro="centos-6" expectation="fail"
  - version=">=2.7,<2.8" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.7,<2.8" distro="debian-stable" expectation="fail"
  - version="" distro="debian-stable" expectation="fail"
  - version="devel" distro="debian-stable" expectation="fail"
  - version=">=2.7,<2.8" distro="debian-unstable" expectation="fail"
  - version="" distro="debian-unstable" expectation="fail"
  - version="devel" distro="debian-unstable" expectation="fail"
  - version=">=2.7,<2.8" distro="fedora-latest" expectation="fail"
  - version="" distro="fedora-latest" expectation="fail"
  - version="devel" distro="fedora-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="fedora-rawhide" expectation="fail"
  - version="" distro="fedora-rawhide" expectation="fail"
  - version="devel" distro="fedora-rawhide" expectation="fail"
  - version=">=2.7,<2.8" distro="opensuse-leap" expectation="fail"
  - version="" distro="opensuse-leap" expectation="fail"
  - version="devel" distro="opensuse-leap" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-rolling" expectation="fail"
  - version="" distro="ubuntu-rolling" expectation="fail"
  - version="devel" distro="ubuntu-rolling" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-latest" expectation="fail"
  - version="" distro="ubuntu-latest" expectation="fail"
  - version="devel" distro="ubuntu-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-devel" expectation="fail"
  - version="" distro="ubuntu-devel" expectation="fail"
  - version="devel" distro="ubuntu-devel" expectation="fail"

matrix:
  allow_failures:
    - env: version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
    - env: version="" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-latest" expectation="fail"
    - env: version="devel" distro="archlinux" expectation="fail"
    - env: version="devel" distro="centos-6" expectation="fail"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-stable" expectation="fail"
    - env: version=">=2.7,<2.8" distro="debian-unstable" expectation="fail"
    - env: version="" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="fedora-latest" expectation="fail"
    - env: version=">=2.7,<2.8" distro="fedora-rawhide" expectation="fail"
    - env: version="" distro="fedora-rawhide" expectation="fail"
    - env: version="devel" distro="fedora-rawhide" expectation="fail"
    - env: version="devel" distro="opensuse-leap" expectation="fail"
    - env: version="devel" distro="ubuntu-rolling"
    - env: version=">=2.7,<2.8" distro="ubuntu-devel" expectation="fail"
    - env: version="" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-latest" expectation="fail"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "JLU2lW2nxLz9rgV/Azw+SJC7WOVCm9rP3BGVHCSD+SueuCAtmcEIWSeoIxSancXBfV323qA/ttywlk7DAD7ZQWfo2pWk9IiQ8ji2+zUV6YmvvmkK6wJtXClnbgFuFe7i6ylMRl1ROlw/1H7n8yo62tlTZWFCJUFBcNBtuK//jY5nh8jlFqSdLCtsw34h4uHlQK1x44B4R2bNU8NCxmrJUgsARt9bwvGAb/04Zd858hfLHpFVPUJVgpa2h6e+caDJLDgjyzJfot4JfGlk5WOwYQM1WIg6pyVJXiFQn/8hywYw9cT/uslStF7W8LHyhWFzUY26b8GYWjKDpeyx58DV02nI8/idvB3OceOOKMkba2cf8rQegQuevbS0rvw347u06CHcbdJaWSm2tfhHqFAMQXhbFyEuezUvHQClCgLCO+ZbKleDCoC49cqPXc+xXueeZAegCxMIxlIfwspWfkk9BNI9pUPyQSsuR6d2y/19t9HiLzoFrA5fheaRKCxJTjLE+RZsmk+jEl+ypyFGV0rJXI1qCwAa8uT2SiIntjadi2XKYxPVnm6v2ey7tM8fjI2HhBRHl7Bpq3A11uhfNbcW6r0z+9RshstGO1ERKRjaX7zO6czceQ1bL4oOppYtjcg58OxbZd8a1WUgKyfIwzS/2WuOTXiGqDwHHCu9qhmIpLM="
  email: false
