---
# tasks file for install_mssql
- name: install repo
  get_url:
    url: https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo
    dest: /etc/yum.repos.d/mssql-server.repo
  when: ansible_distribution == 'Ubuntu'

- name: add apt signing key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: install repo
  yum_repository:
    name: packages-microsoft-com-mssql-server-2017
    state: present
    description: Microsoft MSSQL server
    baseurl: https://packages.microsoft.com/rhel/7/mssql-server-2017
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    

- name: install mssql-server package
  package:
    name: mssql-server
    state: latest
  environment:
    ACCEPT_EULA: Y
  notify:
    - stop existing mssql-server
    - run mssql setup script

- name: start and enable mssql-server
  service:
    name: mssql-server
    state: started
    enabled: yes
  environment:
    ACCEPT_EULA: Y



# - name: stop exsisting mssql-server
#  systemd:
#    name: mssql-server
#    state: stopped

# - name: run mssql setup script
#  command: /opt/mssql/bin/mssql-conf -n setup accept-eula
#  environment:
#    MSSQL_SA_PASSWORD: LiRong11821
#    MSSQL_PID: express
#  become: yes

# - name: restart
#  systemd:
#    name: mssql-server
#    state: restarted
#    enabled: yes
#  become: yes










